


function E = social_conformism_sdt_setup(W,groupNum)
    
    
    %% set parameters
    
    nTests = 100;
    nBlocks = 1;
    
    fixationColor = [ 0,0,0 ];
    fixationSizeDeg = 0.4;
    fixationThicknessDeg = 0.1;
    fixationTextDistDeg = 8;
    
    stimSizeDeg = 10;
    stimContrast = 0.05;
    stimCycDeg = 2;
    stimFadingMeanRat = 0.9;
    stimFadingStdRat = 0.02;
    stimNoiseStd = 0.1;
    
    stcStart = [-15,-10,-5,0];
    stcLength = 50;
    stcStep = 10;
    stcBlocks = 4;
    stcThreshold = 0.80;
    
    baselineTrials = 100;
    baselineBlocks = 4;
    
    durFixSec = 0.5;
    durStimSec = 0.1;
    durGapSec = 0.2;
    durItiSec = 0.5;
    durPauseSec = 1;
    
    textSize = 32;
    textStyle = 0;              % 0=normal,1=bold,2=italic,4=underline,8=outline,32=condense,64=extend
    textFont = 'Arial';
    textColor = 0;
    textFreqHz = 1;
    

    %% convert units
    
    fixationSizeRad = fixationSizeDeg*pi/180;
    fixationThicknessRad = fixationThicknessDeg*pi/180;
    fixationTextDistRad = fixationTextDistDeg*pi/180;
    stimSizeRad = stimSizeDeg*pi/180;
    stimCycRad = stimCycDeg*pi/180;
    
    fixationSizeCm = W.viewingDistCm*tan(fixationSizeRad);
    fixationThicknessCm = W.viewingDistCm*tan(fixationThicknessRad);
    fixationTextDistCm = W.viewingDistCm*tan(fixationTextDistRad);
    stimSizeCm = W.viewingDistCm*tan(stimSizeRad);
    stimCycCm = W.viewingDistCm*tan(stimCycDeg);
    
    fixationSizePix = fixationSizeCm/W.pixSize;
    fixationThicknessPix = fixationThicknessCm/W.pixSize;
    fixationTextDistPix = fixationTextDistCm/W.pixSize;
    stimSizePix = round(stimSizeCm/W.pixSize);
    stimCycPix = stimCycCm/W.pixSize;
    
    
    %% set up design
    
    nGroupTrials = 2*nTests;
    
    snrList = NaN(nGroupTrials,1);
    
    congList = repmat([0;1],nTests,1);
    congList = congList(randperm(nGroupTrials));
    
    
    %% staircases design
    
    stcNumbers = length(stcStart);
    stcTrials = stcNumbers*stcLength;
    
    stcNn = zeros(1,stcNumbers);
    
    stcVal = NaN(stcLength,stcNumbers);
    stcVal(1,:) = stcStart;
    
    stcResp =  NaN(stcLength,stcNumbers);
    
    stcList = repmat(1:stcNumbers,stcLength,1);
    stcList = stcList(randperm(stcNumbers*stcLength));
    
    stcOrder = repmat([1;2],stcLength*stcNumbers/2,1);
    stcOrder = stcOrder(randperm(stcNumbers*stcLength));
    
    
    %% baseline part design
    
    
    
    
    %% generate structure
    E = struct(...
        'nGroupTrials',             	nGroupTrials , ...
        'nBlocks',                      nBlocks , ...
        'fixationColor',                fixationColor , ....
        'fixationSizeDeg',              fixationSizeDeg , ...
        'fixationThicknessDeg',         fixationThicknessDeg , ...
        'fixationTextDistDeg',          fixationTextDistDeg , ...
        'fixationSizeRad',              fixationSizeRad , ...
        'fixationThicknessRad',         fixationThicknessRad , ...
        'fixationTextDistRad',          fixationTextDistRad , ...
        'fixationSizeCm',               fixationSizeCm , ...
        'fixationThicknessCm',          fixationThicknessCm , ...
        'fixationTextDistCm',           fixationTextDistCm' , ...
        'fixationSizePix',              fixationSizePix , ...
        'fixationThicknessPix',         fixationThicknessPix , ...
        'fixationTextDistPix',        	fixationTextDistPix , ...
        'stimContrast',                 stimContrast , ...
        'stimSizeDeg',                  stimSizeDeg , ....
        'stimSizeRad',                  stimSizeRad , ...
        'stimSizeCm',                   stimSizeCm , ...
        'stimSizePix',                  stimSizePix , ...
        'stimCycDeg',                   stimCycDeg , ...
        'stimCycRad',                   stimCycRad , ...
        'stimCycCm',                    stimCycCm , ...
        'stimCycPix',                   stimCycPix , ...
        'stimFadingMeanRat',            stimFadingMeanRat , ...
        'stimFadingStdRat',             stimFadingStdRat , ...
        'stimNoiseStd',                 stimNoiseStd , ...
        'groupNum',                     groupNum , ...
        'durFixSec',                    durFixSec , ...
        'durStimSec',                   durStimSec , ...
        'durGapSec',                    durGapSec , ...
        'durItiSec',                    durItiSec , ...
        'durPauseSec',                  durPauseSec , ...
        'snrList',                      snrList , ...
        'stcNumbers',                  	stcNumbers , ...
        'stcTrials',                    stcTrials , ...
        'stcStart',                     stcStart , ...
        'stcLength',                    stcLength , ...
        'stcStep',                      stcStep , ...
        'stcBlocks',                    stcBlocks , ...
        'stcThreshold',                 stcThreshold , ...
        'stcNn',                        stcNn , ...
        'stcVal',                       stcVal , ...
        'stcResp',                      stcResp , ...
        'stcList',                      stcList , ...
        'stcOrder',                     stcOrder , ...
        'baselineTrials',               baselineTrials , ...
        'baselineBlocks',               baselineBlocks , ...
        'congList',                     congList , ...
        'textSize',                     textSize , ...
        'textStyle',                    textStyle , ...
        'textFont',                     textFont , ...
        'textColor',                    textColor , ...
        'textFreqHz',                   textFreqHz ...
        );


end


